version: '3'
services:
  fastapi:
    build: ./fastapi
    working_dir: /code
    volumes:
      - fastapi-vol:/code
    ports:
    - "9090:80"

  sveltkit:
    build: ./sveltkit
    working_dir: /root/dev
    volumes:
      - sveltkit-vol:/root/dev
    ports:
    - "3000:3000"
    command: /bin/sh -c "sleep 365d & trap 'Shutting down.' TERM; wait"
    depends_on:
    - fastapi

volumes:
  fastapi-vol:
  sveltkit-vol: